### PR TITLE
Initial commit for negative number support

### PR DESCRIPTION
**Pull request by jagkum**
Sorry I have to format your code and add some prop validation in order to use it as per my project

1. Added new prop as allowNegative
2. If allowNegative and you enter '-' anywhere in the input it will add '-' before the prefix
3. If you enter '-' second time and if number is already negative it will remove '-'

### CODE REVIEW

**Comment by s-yadav** [comment]
Can you set indent to 2 and commit again?

**Comment by jagkum** [comment]
@s-yadav  I chnaged tab indent and committed again. Now you can compare easily.

**Comment by radulucaciu** [comment]
This would be helpful to me as well - can this be merged?

**Comment by psalchow** [comment]
+1

**Comment by ShannonStoner** [comment]
+1

**Comment by s-yadav** [comment]
Merged with few fixes

**Pull request merged**
