### PR TITLE
feat: Add flexibility to get other props as a part of render function

### PR DESCRIPTION
**Pull request by nikhil-varma**
## Describe the issue/change
In the current system, we cannot get access to the props passed in the `renderText` method. 

## Describe the changes proposed/implemented in this PR
This PR introduces another parameter in the `renderText` method in order to get the props passed to the component

## Link Github issue if this PR solved an existing issue
Issue: #456 

## Example usage (If applicable)
```
 <NumberFormat
        displayType="text"
        className="foo"
        someRandomProps="someValue"
        value="123"
        renderText={(formattedValue, props) => {
          // Do something with obtained props
          return <span>{formattedValue}</span>;
        }}
      />
```
## Please check which browsers were used for testing
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [x] Safari (iOS)
- [x] Firefox
- [ ] Firefox (Android)

### CODE REVIEW

**Comment by s-yadav** [comment]
@naman03malhotra @ParthS007, CI not working on PRs, can anyone take a look into this.

**Comment by ParthS007** [comment]
I can make PR. @naman03malhotra Please let me know if you have already started working on this.

**Comment by ParthS007** [comment]
@s-yadav I made the PR fixing the CI run. https://github.com/s-yadav/react-number-format/pull/486

After merging my PR, you have to change the `required` status for the CI with the new one.

**Comment by s-yadav** [comment]
@ParthS007, Merged your changes. The action seems working correctly now.

**Comment by nikhil-varma** [comment]
@s-yadav Ready for review 😄

**Comment by ParthS007** [comment]
@nikhil-varma Can you please rebase your branch with the latest master for CI to run. Thanks

**Comment by nikhil-varma** [comment]
@ParthS007 Done! 😄

**Comment by nikhil-varma** [comment]
@s-yadav Please verify if the changes are good to go! 😄

**Comment by s-yadav** [comment]
LGTM, can you add spec for the change.

**Comment by nikhil-varma** [comment]
@s-yadav Specs are added. Please review if it looks good! Thanks!

**Review by s-yadav — APPROVED** [review]

**Comment by nikhil-varma** [comment]
@s-yadav Should we go ahead and close the linked issue? Or wait until we release the new patch/version and then do it? What would you suggest?

**Comment by s-yadav** [comment]
Will release a new version. 
One thing we missed, we will have to update the readme to reflect this new param.

**Comment by nikhil-varma** [comment]
@s-yadav Right! I will update the readme and create a PR for this.

**Pull request merged**
