### PR TITLE
feat: added support for persian numeral input

### PR DESCRIPTION
**Pull request by electather**
#### Describe the issue/change
added support for Persian numeral which automatically formats it to standard English numeral 

#### Add CodeSandbox link to illustrate the issue (If applicable)
try inputting ۱۲۳۴۵۶۷۸۹۰ in the input

#### Describe specs for failing cases if this is an issue (If applicable)
none

#### Describe the changes proposed/implemented in this PR
added an optional prop `convertPersianDigits`  which triggers a customized regex and a formatter 

#### Link Github issue if this PR solved an existing issue
none

#### Example usage (If applicable)
try inputting ۱۲۳۴۵۶۷۸۹۰ in the input

#### Please check which browsers were used for testing
- [ *] Chrome
- [* ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ *] Firefox
- [ ] Firefox (Android)

### CODE REVIEW

**Comment by s-yadav** [comment]
Instead of adding checks specific for Persian input, I think we should allow user to provide the numeric regex as props default  to [0-9].

**Comment by s-yadav** [comment]
Also, @nikhil-varma Can we run prettier on all files once, so the PR doesn't include the prettier changes.

**Comment by nikhil-varma** [comment]
@s-yadav sure! Sounds good

**Comment by electather** [comment]
@s-yadav so, providing a prop like inputRegex that defaults to /d and a function that transforms that input to English numerals.
or we can do it in an array like:
```ts
{
  regex: string,
  transformer : () => number;
}
```

**Comment by s-yadav** [comment]
@electather Sorry for replying late. But I didn't get the use case of providing transformer. This can remain outside of NumberFormat right?

**Comment by electather** [comment]
One place that it could've helped is the onValueChange where we have the parsed values. If user decides to override the regex then the input cannot be converted to int and user can only receive the formatted string value. 
But forcing the user to provide transformer on regex override will prevent this issue

**Comment by s-yadav** [comment]
Make sense, not just on onValueChange. Internally we use numbers to round to define precision. So conversion is indeed needed. 
The other approach to do this can be.
```js
customNumerals: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] // where people can provide numeric mapping based on the numeral they want to support.
```
With this we can create a regex. `new RegExp(customNumerals.join('|'))`
And can also apply the transformation in the lib only.

The only problem is what if the customNumerals do not follow character to character map, like Roman Numerals. People might expect this numeral as well to work which would be very tricky to implement.

**Comment by electather** [comment]
@s-yadav seems like a great idea. i'm gonna close this pull request and start working on a new one. ( since it has little in common with what is currently purposed)

**Pull request closed without merging**
